Real data student
SELab-2/UGent-2 pull request #158
Opened 2024-04-12 17:49 UTC by ALBERICLOOS

Closes #163

2024-04-15 12:34 UTC, ALBERICLOOS commented on frontend/src/main.tsx
> +                <Route id={CREATE_PROJECT_TEACHER_ID} path={"/teacher/projects/create"} element={<CreateProject/>}
Een leerkracht moet kunnen kiezen aan welk vak hij een project linkt, we moeten dus al zijn vakken ophalen.

2024-04-15 12:35 UTC, ALBERICLOOS commented on frontend/src/components/ProjectStudentComponent.tsx
> +                            <label className={"has-text-danger"}>{props.project.status}</label>}
Ik zal deze comment nog laten openstaan zodat ik het niet vergeet te veranderen later

2024-04-15 12:37 UTC, ALBERICLOOS commented on frontend/src/pages/student/ProjectsViewStudent.tsx
> +        switch (project_item.submission_state) {
Ik ga dit nog ook nog aanpassen als Ruben eenmaal heet gemerged.

2024-04-15 12:51 UTC, ALBERICLOOS commented
> Hoe test ik dit best? Want mijn gebruiker heeft geen data.

Ik denk tot we best wachten tot al de rest in de main zit, ik zal deze PR terug op draft zetten

2024-04-15 15:39 UTC, ALBERICLOOS commented
Ik ben klaar met alle echte data te laden voor een student, hier zijn de aanpassingen die je moet doen om het lokaal te runnen:
* pull voor de backend van de main branch
* run zeker eerste eens `fill_database_mock.py`
* vervolgens moet je in `user.py` deze functie veranderen:
```
@users_router.get("/users/{uid}", tags=[Tags.USER], summary="Get a certain user.")
def admin_get_user(request: Request, uid: int) -> User:
    session = request.state.session
    return get(session, User, uid)
```
* Verander dit in `extensions.py`
```
engine = create_engine(DB_URI, pool_size=60, max_overflow=80, pool_timeout=30, pool_recycle=1800)
```
* voor de frontend moet je van deze branch pullen `projectViewStudentRealData`
* zet in `root.tsx` debug op `true`
* zet in `LoginScreen.tsx` de url naar deze, de uid op het einde is een user die je zelf kan kiezen (uid = 2 is Alberic)
```
if (DEBUG) {
        url = 'http://127.0.0.1:8000/api/fake-login?uid=2'
    }
```
* verwijder je  lokale cookies
* run het programma

2024-04-15 20:02 UTC, matt01y commented on frontend/src/main.tsx
> +                <Route id={CREATE_PROJECT_TEACHER_ID} path={"/teacher/projects/create"} element={<CreateProject/>}
Doe dan maar 1 id gaat het duidelijker maken.

2024-04-15 20:10 UTC, matt01y commented
Dankje om snel te antwoorden.
En ook om zo een mooie uitleg te geven.
Ik ga wel wachten met nog een review te geven tot rubben zijn branch gemerged is.
Had eig gehoopt die vandaag al gemerged te zien.

2024-04-16 13:54 UTC, ALBERICLOOS commented
Ik ga nu de merge conflicts oplossen met main en dan kijken om I18N toe te voegen

2024-04-16 14:54 UTC, ALBERICLOOS commented
Voor de review moet je nog altijd dezelfde aanpassingen doen zoals hier: https://github.com/SELab-2/UGent-2/pull/158#issuecomment-2057159878
Normaal zou alles nu moeten werken :smile:

2024-04-17 09:29 UTC, matt01y requested changes
Al bij al een goede pr, gewoon nog hier en daar een i18n vergeten

2024-04-17 09:29 UTC, matt01y commented on frontend/src/pages/student/ProjectViewStudent.tsx
> +            there was an error loading the project
i18n

2024-04-17 09:29 UTC, matt01y commented on frontend/src/pages/student/ProjectViewStudent.tsx
> +    }
Dit kan zonder switch

2024-04-17 09:29 UTC, matt01y commented on frontend/src/pages/student/ProjectsViewStudent.tsx
> +        switch (project_item.submission_state) {
.

2024-04-17 09:29 UTC, matt01y commented on frontend/src/pages/teacher/CreateProject.tsx
> +    console.log(data.courses);
.

2024-04-17 09:29 UTC, matt01y commented on frontend/src/pages/teacher/CreateProject.tsx
> +            there was an error loading the courses
i18n

2024-04-17 09:29 UTC, matt01y commented on frontend/src/pages/teacher/ProjectViewTeacher.tsx
> +            there was an error loading the project
i18n

2024-04-17 17:47 UTC, ALBERICLOOS commented on frontend/src/dataloaders/loader_helpers/SharedFunctions.ts
> +        projects = projects.filter(project => project.project_visible)
Toen dacht ik nog dat studenten ook gearchiveerde projecten konden zien, ik heb het nu weggedaan

2024-04-18 07:42 UTC, matt01y approved these changes
Dankje  voor de changes.

2024-04-18 07:42 UTC, merged