fix: load course after creating and show deadline as -
SELab-2/UGent-2 pull request #243
Opened 2024-04-29 09:47 UTC by EmmaVandewalle

Closes #215

2024-04-29 12:01 UTC, ALBERICLOOS commented
Closes #239

2024-04-30 09:57 UTC, matt01y requested changes
ziet er goed uit, maar mss alles direct i18n maken terwijl je er toch aan bezig bent?

2024-04-30 09:57 UTC, matt01y commented on frontend/src/components/AddWarning.tsx
> -                Voeg toe
Mss zou het nu een goed moment zijn om dit allemaal i18n te maken terwijl je er toch aan bezig bent?

2024-05-02 14:12 UTC, matt01y reviewed
Er is lijk zo een raar patroon dat meerdere keren optreed. Is dit een must? Of kan dit zoals in de eerste comment voorgesteld wordt?

2024-05-02 14:12 UTC, matt01y commented on frontend/src/components/Archive.tsx
> +                        <RegularButton placeholder={`${t('popups.yes')}`} add={false} styling={"is-danger"} onClick={() => {}}/>
Kan je niet gewoon 
```ts
t('popups.yes')
```
meegeven ipv het nog eens te nesten in een string?

2024-05-02 14:12 UTC, matt01y commented on frontend/src/components/CopyLink.tsx
> +                        <RegularButton placeholder={`${t('popups.share_link')}`} add={false} styling={"is-success"} onClick={() => {}}/>
Hier ook?

2024-05-12 19:11 UTC, matt01y approved these changes

2024-05-12 19:11 UTC, merged