Join course
SELab-2/UGent-2 pull request #252
Opened 2024-04-29 18:21 UTC by matt01y

2024-05-01 12:49 UTC, EmmaVandewalle commented
Closes #234

Ik zal eerst nog layout voorzien

2024-05-06 09:09 UTC, EmmaVandewalle commented
Moet die error niet gewoon een redirect zijn naar de bestaande error.tsx?

2024-05-17 07:09 UTC, ALBERICLOOS requested changes

2024-05-17 07:09 UTC, ALBERICLOOS commented on frontend/src/dataloaders/JoinCourse.ts
> +    console.log(course_id)
foei foei foei

2024-05-17 07:30 UTC, ALBERICLOOS approved these changes
Heel goed gedaan matjas!

2024-05-17 07:30 UTC, merged