Global and extension constraint
SELab-2/UGent-2 pull request #263
Opened 2024-05-04 15:22 UTC by lbarraga

In deze PR heb ik
- Constraints gerefactored om properder te maken
- OnlyPresentConstraint verwijderd
- Global constraints geimplementeerd 
- De testen herschreven en properder gemaakt
- Documentatie geschreven te vinden in de README.md

2024-05-04 15:26 UTC, lbarraga commented
closes #263

2024-05-05 09:27 UTC, rubben-88 commented
Ik heb de documentatie eens doorgelezen en alles ziet er goed en duidelijk uit. Wat me enkel een beetje vreemd lijkt is dat in de ConstraintResult's er vaak een veld sub_constraint_results is die enkel een lege lijst toelaat. Op zich is dat echter geen probleem zolang het werkt. 

De testen heb ik ook eens gerunt en daarbij kom ik een error uit bij test_everything_not_ok.py de laatste test test_no_exe_files_globally uit dat de assertEqual niet gelijk is (KeyError: 'src/utils'). Ook zijn er enkele testfiles waarvan if __name__ == "__main__" ontbreekt.

2024-05-05 13:13 UTC, rubben-88 commented
Ook staat er geen info in de README over een GLOBAL constraint. Enkel over GlobalConstraintResult.

2024-05-05 17:15 UTC, rubben-88 commented
Blijkbaar is ook de OnlyPresentConstraint weg zie ik net. Is het nu nog mogelijk om onderscheid te maken tussen een folder waar x, y & z moet in zitten, maar voor de rest niets anders en een folder waar x, y & z in moet zitten, maar andere mogen ook?

2024-05-09 10:12 UTC, lbarraga commented
Ik heb een bug gevonden die er voor zorgt dat de testen de global constraint functionaliteit niet correct testen. Ik zal dit eerst nog moeten oplossen. @rubben-88 Ik zal er ook voor zorgen dat er geen lege sub_constraint_result lijsten zijn bij subconstraints die dit niet nodig hebben (bv `FileSubconstraintResult`)

2024-05-09 14:27 UTC, lbarraga commented
> Ik heb de documentatie eens doorgelezen en alles ziet er goed en duidelijk uit. Wat me enkel een beetje vreemd lijkt is dat in de ConstraintResult's er vaak een veld sub_constraint_results is die enkel een lege lijst toelaat. Op zich is dat echter geen probleem zolang het werkt.
> 
> De testen heb ik ook eens gerunt en daarbij kom ik een error uit bij test_everything_not_ok.py de laatste test test_no_exe_files_globally uit dat de assertEqual niet gelijk is (KeyError: 'src/utils'). Ook zijn er enkele testfiles waarvan if **name** == "**main**" ontbreekt.

De testen lijken lokaal en op github te werken. De lege sub_constraint_results lijsten heb ik gefixt in  beb1412. Dat was idd niet zo intuitief.

2024-05-09 14:28 UTC, lbarraga commented
> Ook staat er geen info in de README over een GLOBAL constraint (uit je voorbeeld) en weet ik niet echt goed wat je hier mee bedoelt.

Dit heb ik inderdaad over het hoofd gezien. Ik heb het opgelost in ad9db3b

2024-05-09 14:32 UTC, lbarraga commented
> Blijkbaar is ook de OnlyPresentConstraint weg zie ik net. Is het nu nog mogelijk om onderscheid te maken tussen een folder waar x, y & z moet in zitten, maar voor de rest niets anders en een folder waar x, y & z in moet zitten, maar andere mogen ook?

Ik heb dit weggelaten omdat dit de code vrij veel compliceerde in extra checks. Als je zegt dat enkel "X" aanwezig moet zijn, dan weet je op voorhand niet of dit een map is of een bestand, en bijgevolg kan je ook niet zeggen of dat dan subconstraints mag hebben. Het kan echter met veel gepruts (tegen de zin van pyright), maar ik denk dat frontend met de huidige checks al genoeg werk zal hebben. We kunnen het echter herzien moesten we tijd over hebben.

2024-05-09 14:34 UTC, lbarraga commented
> Er ontbreekt nog een constraint om enkel bepaalde extensies toe te laten. Waarom heb je OnlyPresentConstraint verwijderd?

Klopt, dit is toegevoegd in 9b91bc7

2024-05-12 14:30 UTC, msathieu requested changes
`fill_database_mock.py` moet nog aangepast worden.

2024-05-12 17:53 UTC, msathieu approved these changes

2024-05-12 17:53 UTC, merged