feat: teacher can leave course + archive when needed
SELab-2/UGent-2 pull request #329
Opened 2024-05-20 14:31 UTC by EmmaVandewalle

2024-05-20 17:07 UTC, matt01y requested changes

2024-05-20 17:07 UTC, matt01y commented on frontend/src/components/LeaveCourseTeacher.tsx
> +    const navigate = useNavigate();
Waarom gebruik je niet gewoon de echte naam ipv dit nog eens te gaan hernoemen?

2024-05-20 17:07 UTC, matt01y commented on frontend/src/components/LeaveCourseTeacher.tsx
> +                alert("There was an error while trying to leave this course, please try again.");
i18n?

2024-05-20 17:07 UTC, matt01y commented on frontend/src/components/LeaveCourseTeacher.tsx
> +            alert("There was an error while trying to leave this course, please try again.");
i18n?

2024-05-22 12:09 UTC, EmmaVandewalle commented on frontend/src/components/LeaveCourseTeacher.tsx
> +    const navigate = useNavigate();
Ik heb andere mensen hun stijl gevolgd dat er al stond van ervoor

2024-05-22 12:46 UTC, matt01y approved these changes

2024-05-22 12:47 UTC, merged